### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Radu-Raicea** [openobserve/pino-openobserve#4]
When can we expect types for this?

**Comment by Radu-Raicea** [comment]
@ktx-kirtan

**Comment by kvenn** [comment]
https://github.com/openobserve/pino-openobserve/issues/2#issuecomment-2408158216

This should be pretty close.

**Comment by ktx-kirtan** [comment]
Working on this. You will get it soon

**Comment by ktx-kirtan** [comment]
Typescript support added with the new beta release: https://www.npmjs.com/package/@openobserve/pino-openobserve/v/0.1.0-beta.0

Please try it out and let us know if any issues
